---
name: 'Registration: Module 1 - Computing Basics'
about: Register for the HEMI ATOMIC Workshop Module 1
title: "[Registration for Module 1]"
labels: ''
assignees: ajsierakowski
body:
  - type: input
    id: name_first
    attributes:
      label: First name
    validations:
      required: true
  - type: input
    id: name_last
    attributes:
      label: Last name
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email address
      placeholder: email@example.com
    validations:
      required: true

---


